table transacoes
	lineageTag: 763b869c-bb70-4671-8109-7c15e388da19

	measure 'Valor Total' = SUM(transacoes[Total])
		displayFolder: Medidas
		lineageTag: f56f558f-b62e-4e0d-a719-252f2bdf39e5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotação corrigida' = ```
			
			
			VAR __DataCtx = MAX(calendario[Data]) 
			
			VAR __UltimaDataComCotacao = 
			    CALCULATE(
			        LASTNONBLANK(calendario[Data], [Cotação do dia]),
			        calendario[Data] <= __DataCtx
			    )
			
			RETURN
			    CALCULATE(
			        [Cotação do dia],
			        calendario[Data] = __UltimaDataComCotacao
			    )
			
			```
		displayFolder: Medidas
		lineageTag: 413da80f-b051-4e36-9473-5fd929d17cd8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total R$' = ```
			
			SUMX(
			    moedas,
			    SUMX(
			        calendario,
			        COALESCE([Cotação corrigida], 1) * [Valor Total] 
			    )
			) 
			```
		displayFolder: Medidas
		lineageTag: 6b1a594e-51fa-4dc4-ac56-7d0191b875ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: double
		displayFolder: Colunas
		lineageTag: 265e40f6-1a15-49ea-a588-87f7fcdb8284
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: dd/mm/yy
		displayFolder: Colunas
		lineageTag: 6644a4a3-1e26-4147-aed8-39820f1680ca
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Total
		dataType: double
		displayFolder: Colunas
		lineageTag: d2aba532-588a-4c36-9d78-21c758a3515b
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: 2e303283-92e6-4913-8ab8-aa7044a8f8ad
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	partition transacoes = m
		mode: import
		queryGroup: Fatos
		source = ```
				let
				    source = Excel.Workbook(
				        File.Contents(base_transacoes), 
				        true, 
				        null
				    ),
				    
				    transacoes_Table = source{[Item="transacoes",Kind="Table"]}[Data],
				    
				    datesRestricted = Table.SelectRows(
				        transacoes_Table, 
				        each [Data] >= data_inicial and [Data] <= data_final
				    )
				in
				    datesRestricted
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

